### PR TITLE
V0

### LINKED ISSUE #4: Main ECU state machine/class

### LINKED ISSUE #20: separate data and control CAN

### PR DESCRIPTION
**Pull request by yamaan93**
closes #4 
closes #20 

I've deemed the toque map not to be needed for V0, just a linear interpolation is enough to make the car drive. Torque map will be part of future version. 

I also don't have the HSD enables/disables for the pre-charge states because I would rather wait till I have the inverter on a bench to be able to test those properly first.

### CODE REVIEW

**Comment by towner-10** [comment]
Do we need to include the RPi Python code here, or should it go somewhere else?

Also, we should maybe make a graph of the state transitions just so that its easy to see if there are any issues in the future. Otherwise looks good!

**Review by towner-10 — APPROVED** [review]
Congrats on V0!!!

**Comment by yamaan93** [comment]
> Do we need to include the RPi Python code here, or should it go somewhere else?

Yes it makes sense to keep tests with the repo being tested. Just to be clear this isn't the actual script that works. I have one that works but it's locally on an RPi. I'm trying to convert it to a script that runs on the local PC and leverages the RPi as "remote GPIO" instead (that could be swapped with a USB DAC/ADC interface later) since developing on an RPi is kinda slow.

> Also, we should maybe make a graph of the state transitions just so that its easy to see if there are any issues in the future. 

way ahead of you
ECU_state_machine drawio

**Comment by towner-10** [comment]
> way ahead of you ECU_state_machine drawio

Let's add this to the repo as well, maybe in the README since it will help anybody looking at the code kinda decipher what is going on in the `state_machine.cpp` file.

**Pull request merged**
